### PR TITLE
Generalization of solver

### PR DESCRIPTION
**Pull request by bohlender**
Hey @phlo,
I like your idea of generalising the plugin to support arbitrary SMT solvers. Do you have any plans of merging your fork back, since I'd like to have this functionality in the plugin too?

No pressure though - it's no problem if you want to continue with this fork on your own or simply have other plans for it. I just thought I'd ask before duplicating functionality. You're welcome to contribute.

### CODE REVIEW

**Comment by phlo** [comment]
Ahoj @bohlender!

First of all: thank you so much for your work on this plugin! I was looking around for a new SMT-LIB plugin and found yours to be the best, all I tried before were rather unsatisfiable ;) Since I'm using [boolector](http://fmv.jku.at/boolector) and love your in-vim evaluation feature, an extension to support any SMT solver was only logical. This is why I forked it: to try this generalization and being able to use it immediately. I planned to ask you if you want me to contribute and if so, merge it back.. So I'm glad you like it :) But after finding a beta tester - my professor [Armin Biere](http://fmv.jku.at/biere) - I hesitated since he had some installation issue, which I wanted to resolve first. Unfortunately, we weren't able to do so as he was at [TACAS](https://www.etaps.org/index.php/2018/tacas) last week. That's also why I updated the README's 'Installation' section.

So if you really want to merge, I'd be happy to contribute! I just have one concern regarding the plugin's name: if we generalize it, `vim-z3-smt2` might be too specific - that's why I renamed it to `vim-smt2`. Also, I'm kind of a noob when it comes to these GitHub features, so I don't really know what I would have to do.

Cheers,
@phlo

---

**PS:** Ich bin aus Oesterreich und spreche daher auch so etwas aehnliches wie Deutsch wenn's dir lieber ist ;)

---

**PPS:** If you'r doing hardware stuff and extensively use bitvectors, check out [boolector](http://fmv.jku.at/boolector)!

---

**PPPS:** Thanks to RWTH Aachen for hosting my preferred [Gentoo](https://www.gentoo.org) mirror!

**Comment by bohlender** [comment]
Hey @phlo,

let's keep the communication in English for future reference, or in case someone else wants to chime in. Coming from a formal methods background myself, I already am a user of Boolector and happy to hear that you guys (with A.Biere being pretty famous) try to use this plugin.

To begin with, I will merge your work into a feature branch myself and make sure everything still works as expected. Then I will update the master branch and change the name to ``vim-smt2`` as you suggested.

I'm not an expert regarding GitHub's collaboration features either, but I will add you as a collaborator so you can push future contributions directly -- without the need for pull requests.

**Comment by phlo** [comment]
Hi @bohlender,

sounds like a plan! So as soon as you complete these further steps I will archive xor delete the fork's repository.

Prof. Biere also suggested me to announce the plugin on the [SMT-Lib Google group](https://groups.google.com/forum/#!forum/smt-lib), but didn't do it yet as I wanted to ask if maybe you want to make the post (since you'r the original author)?

Nice to get to know another Boolector user! I forked you'r repository after a discussion with the main developers (@aniemetz & @mpreiner), where we agreed upon the need for a decent vim plugin ;)

Looking forward to collaborate with you!

**Comment by bohlender** [comment]
Hey @phlo,

I'm not using Google groups, so feel free to announce the plugin once we have everything up and running back in the master branch.

While your modifications defaulted `g:smt2_solver_command` to `boolector`, I've set up defaulting to either `z3` or `boolector` (checking in this order whether one of the executables can be found in `$PATH`). We can change the order though if this is a problem. I just find it reasonable to have `z3` as default since its extensions are supported by the highlighting.

I've also adapted the `README.md` slightly to account for the change and make the installation instructions a bit leaner (moved some stuff to FAQ). Please have a look whether anything needs discussion or just make reasonable changes you find necessary (you _should_ have push access).

To me, the current state looks fine. I will merge it into the master and rename the repository to `vim-smt2` once you're okay with the current state.

**Comment by phlo** [comment]
Hey @bohlender,

alright.. looking good! I just made some cosmetic changes to test my push access and it seems to work :)

The `README.md`'s installation instruction table looks nice! Sorry for breaking the old one. I even tried to vertically center the enumerations inside the table cells but failed (should have tested it using the preview feature of some GitHub comment box). Regarding the former post installation section: I just put it there to make sure `filetype plugin` is enabled, since I suspect it being the problem encountered by @arminbiere. But it's indeed much more suitable in the FAQ / troubleshooting section.

I was also thinking about switching back to `z3` as the default solver for the merged version, but forgot to mention it in my previous replies. Anyhow, I really like your solution! This way we could add other major solvers to the list and get rid of having a specific default in general. I would even go as far as supporting their language extensions too. Shall we?

**Comment by bohlender** [comment]
Hey @phlo,

I guess then we're done with merging your modifications back. I'll update the master any minute.

Regarding further extensions, like support of other major solvers and/or their extensions, we should open issues and discuss the realisation there. For example I'm not sure how we would go about supporting several SMT-LIB2 extensions: merging everything into a single grammar might be conflicting or result in inconsistent/unexpected highlighting, while having separate grammars will require switching depending on the solver.

I'm in favour of improving the plugin. Just open up an issue for every feature that you have in mind - maybe this will attract even more people interested in contributing ;)

**Pull request merged**
